### ISSUE TITLE
Automatically Post to Social Media 

### ISSUE THREAD

**Issue by putheakhem** [Sebobo/Shel.Blog#11]
As a blog admin if I have a new feature which allows our site post directly to social media such as facebook ( follow open graph role ) or twitters. 
It's just my ideas 
Thanks

**Comment by Sebobo** [comment]
The idea basically makes sense but I think it's quite some work to support multiple systems.
I won't be able to implement that in the near future.
But you or anyone else is welcome to do a PR.

**Comment by Sebobo** [comment]
I'll close this. Please provide a PR if needed.
