### ISSUE TITLE
Sorting the `BlogFeed` entries

### ISSUE THREAD

**Issue by dgrammlich** [Sebobo/Shel.Blog#3]
Hi @Sebobo,

thanks for your very cool and simple blog package. :)
I use it in my website and wanted to sort the `BlogFeed` descending by date. The only way to do so was to write the following Fusion code:
```
prototype(Shel.Blog:BlogFeedContent) {
    feedEntries.@process {
        sort = ${q(value).sortBlogEntries('publicationDate', 'DESC').get()}
    }
}
```
![screenshot from 2016-11-08 16-07-03](https://cloud.githubusercontent.com/assets/5312377/20104557/bb5012ee-a5ce-11e6-8b8a-ff03aaf50c2e.png)

It would be nice to have a possibility in the inspector to configure it like in the `LatestBlogEntries`. :)

Thanks in advance!

**Comment by Sebobo** [comment]
This feature was actually prepared in the code for a long time but the field for selecting the sorting
was missing ;)
Released 2.1.0 including the change and a small template change.
