### ISSUE TITLE
Give a more details of ReadMe to help newer with Neos

### ISSUE THREAD

**Issue by putheakhem** [Sebobo/Shel.Blog#9]
As a new with neos like me. I have a problem with the configuration and using your package. If you kindly give more clear instructions. Thanks

**Comment by Sebobo** [comment]
Hi,

what information are you missing exactly?

**Comment by putheakhem** [comment]
This one I can't figure out where I should override.

You can overwrite and modify the different content elements to your needs:
* `Shel.Blog:BlogEntry` - A single blog post
* `Shel.Blog:BlogFeed` - The container for blog entries which also works as archive and atom feed
* `Shel.Blog:LatestBlogEntries` - Renders a sorted list of blog posts for example on your homepage 

and the other one is when I create a new site and I use this package.
Then my site could have functionality as your blog. ( i already check your blog post)

**Comment by Sebobo** [comment]
Sorry, still not sure what your missing.

After you install the package you have the 3 additional node types.
Is the problem how to use them and where or how to change the template for example?

**Comment by putheakhem** [comment]
I already done and can use it.

**Comment by Sebobo** [comment]
ok great.
